[package]
name = "agc014"
version = "0.1.0"
authors = ["emanon001 <emanon001@gmail.com>"]
edition = "2018"

[package.metadata.cargo-compete]
config = "../compete.toml"

[package.metadata.cargo-compete.bin]
a = { name = "agc014-a", problem = "https://atcoder.jp/contests/agc014/<FIXME: screen name of the problem>"}
b = { name = "agc014-b", problem = "https://atcoder.jp/contests/agc014/<FIXME: screen name of the problem>"}
c = { name = "agc014-c", problem = "https://atcoder.jp/contests/agc014/<FIXME: screen name of the problem>"}
d = { name = "agc014-d", problem = "https://atcoder.jp/contests/agc014/<FIXME: screen name of the problem>"}
e = { name = "agc014-e", problem = "https://atcoder.jp/contests/agc014/<FIXME: screen name of the problem>"}
f = { name = "agc014-f", problem = "https://atcoder.jp/contests/agc014/<FIXME: screen name of the problem>"}

# dependencies added to new project
[dependencies]
proconio = "*"

[profile.release]
lto = true
panic = 'abort'

[[bin]]
name = "agc014-a"
path = "./src/bin/a.rs"

[[bin]]
name = "agc014-b"
path = "./src/bin/b.rs"

[[bin]]
name = "agc014-c"
path = "./src/bin/c.rs"

[[bin]]
name = "agc014-d"
path = "./src/bin/d.rs"

[[bin]]
name = "agc014-e"
path = "./src/bin/e.rs"

[[bin]]
name = "agc014-f"
path = "./src/bin/f.rs"
