[package]
name = "language-test-202001"
version = "0.1.0"
authors = ["emanon001 <emanon001@gmail.com>"]
edition = "2018"

[package.metadata.cargo-compete]
config = "../compete.toml"

[package.metadata.cargo-compete.bin]
abc049c = { name = "language-test-202001-abc049c", problem = "https://atcoder.jp/contests/language-test-202001/<FIXME: screen name of the problem>"}
abc081a = { name = "language-test-202001-abc081a", problem = "https://atcoder.jp/contests/language-test-202001/<FIXME: screen name of the problem>"}
abc081b = { name = "language-test-202001-abc081b", problem = "https://atcoder.jp/contests/language-test-202001/<FIXME: screen name of the problem>"}
abc083b = { name = "language-test-202001-abc083b", problem = "https://atcoder.jp/contests/language-test-202001/<FIXME: screen name of the problem>"}
abc085b = { name = "language-test-202001-abc085b", problem = "https://atcoder.jp/contests/language-test-202001/<FIXME: screen name of the problem>"}
abc085c = { name = "language-test-202001-abc085c", problem = "https://atcoder.jp/contests/language-test-202001/<FIXME: screen name of the problem>"}
abc086a = { name = "language-test-202001-abc086a", problem = "https://atcoder.jp/contests/language-test-202001/<FIXME: screen name of the problem>"}
abc086c = { name = "language-test-202001-abc086c", problem = "https://atcoder.jp/contests/language-test-202001/<FIXME: screen name of the problem>"}
abc087b = { name = "language-test-202001-abc087b", problem = "https://atcoder.jp/contests/language-test-202001/<FIXME: screen name of the problem>"}
abc088b = { name = "language-test-202001-abc088b", problem = "https://atcoder.jp/contests/language-test-202001/<FIXME: screen name of the problem>"}
l = { name = "language-test-202001-l", problem = "https://atcoder.jp/contests/language-test-202001/<FIXME: screen name of the problem>"}
m = { name = "language-test-202001-m", problem = "https://atcoder.jp/contests/language-test-202001/<FIXME: screen name of the problem>"}
practicea = { name = "language-test-202001-practicea", problem = "https://atcoder.jp/contests/language-test-202001/<FIXME: screen name of the problem>"}

# dependencies added to new project
[dependencies]
# alga = "=0.9.3"
# ascii = "=1.0.0"
# bitset-fixed = "=0.1.0"
# either = "=1.5.3"
# fixedbitset = "=0.2.0"
# getrandom = "=0.1.14"
# im-rc = "=14.3.0"
# indexmap = "=1.3.2"
itertools = "=0.9.0"
itertools-num = "=0.1.3"
# lazy_static = "=1.4.0"
# libm = "=0.2.1"
# maplit = "=1.0.2"
# nalgebra = "=0.20.0"
# ndarray = "=0.13.0"
num = "=0.2.1"
ordered-float = "=1.0.2"
# permutohedron = "=0.2.4"
# petgraph = "=0.5.0"
proconio = { version = "=0.3.6", features = ["derive"] }
# rand = { version = "=0.7.3", features = ["small_rng"] }
regex = "=1.3.6"

[profile.release]
lto = true
panic = 'abort'

[[bin]]
name = "language-test-202001-abc049c"
path = "./src/bin/abc049c.rs"

[[bin]]
name = "language-test-202001-abc081a"
path = "./src/bin/abc081a.rs"

[[bin]]
name = "language-test-202001-abc081b"
path = "./src/bin/abc081b.rs"

[[bin]]
name = "language-test-202001-abc083b"
path = "./src/bin/abc083b.rs"

[[bin]]
name = "language-test-202001-abc085b"
path = "./src/bin/abc085b.rs"

[[bin]]
name = "language-test-202001-abc085c"
path = "./src/bin/abc085c.rs"

[[bin]]
name = "language-test-202001-abc086a"
path = "./src/bin/abc086a.rs"

[[bin]]
name = "language-test-202001-abc086c"
path = "./src/bin/abc086c.rs"

[[bin]]
name = "language-test-202001-abc087b"
path = "./src/bin/abc087b.rs"

[[bin]]
name = "language-test-202001-abc088b"
path = "./src/bin/abc088b.rs"

[[bin]]
name = "language-test-202001-l"
path = "./src/bin/l.rs"

[[bin]]
name = "language-test-202001-m"
path = "./src/bin/m.rs"

[[bin]]
name = "language-test-202001-practicea"
path = "./src/bin/practicea.rs"
