[package]
name = "past202203-open"
version = "0.1.0"
edition = "2021"

[package.metadata.cargo-compete]
config = "../compete.toml"

[package.metadata.cargo-compete.bin]
a = { name = "past202203-open-a", problem = "https://atcoder.jp/contests/past202203-open/<FIXME: screen name of the problem>"}
b = { name = "past202203-open-b", problem = "https://atcoder.jp/contests/past202203-open/<FIXME: screen name of the problem>"}
c = { name = "past202203-open-c", problem = "https://atcoder.jp/contests/past202203-open/<FIXME: screen name of the problem>"}
d = { name = "past202203-open-d", problem = "https://atcoder.jp/contests/past202203-open/<FIXME: screen name of the problem>"}
e = { name = "past202203-open-e", problem = "https://atcoder.jp/contests/past202203-open/<FIXME: screen name of the problem>"}
f = { name = "past202203-open-f", problem = "https://atcoder.jp/contests/past202203-open/<FIXME: screen name of the problem>"}
g = { name = "past202203-open-g", problem = "https://atcoder.jp/contests/past202203-open/<FIXME: screen name of the problem>"}
h = { name = "past202203-open-h", problem = "https://atcoder.jp/contests/past202203-open/<FIXME: screen name of the problem>"}
i = { name = "past202203-open-i", problem = "https://atcoder.jp/contests/past202203-open/<FIXME: screen name of the problem>"}
j = { name = "past202203-open-j", problem = "https://atcoder.jp/contests/past202203-open/<FIXME: screen name of the problem>"}
k = { name = "past202203-open-k", problem = "https://atcoder.jp/contests/past202203-open/<FIXME: screen name of the problem>"}
l = { name = "past202203-open-l", problem = "https://atcoder.jp/contests/past202203-open/<FIXME: screen name of the problem>"}
m = { name = "past202203-open-m", problem = "https://atcoder.jp/contests/past202203-open/<FIXME: screen name of the problem>"}
n = { name = "past202203-open-n", problem = "https://atcoder.jp/contests/past202203-open/<FIXME: screen name of the problem>"}
o = { name = "past202203-open-o", problem = "https://atcoder.jp/contests/past202203-open/<FIXME: screen name of the problem>"}

# dependencies added to new project
[dependencies]
alga = "=0.9.3"
ascii = "=1.0.0"
bitset-fixed = "=0.1.0"
either = "=1.5.3"
fixedbitset = "=0.2.0"
getrandom = "=0.1.14"
im-rc = "=14.3.0"
indexmap = "=1.3.2"
itertools = "=0.9.0"
itertools-num = "=0.1.3"
lazy_static = "=1.4.0"
libm = "=0.2.1"
maplit = "=1.0.2"
nalgebra = "=0.20.0"
ndarray = "=0.13.0"
num = "=0.2.1"
ordered-float = "=1.0.2"
permutohedron = "=0.2.4"
petgraph = "=0.5.0"
proconio = { version = "=0.3.6", features = ["derive"] }
rand = { version = "=0.7.3", features = ["small_rng"] }
regex = "=1.3.6"
rustc-hash = "=1.1.0"
smallvec = "=1.2.0"
superslice = "=1.0.0"
text_io = "=0.1.8"
whiteread = "=0.5.0"

[profile.release]
lto = true
panic = 'abort'

[[bin]]
name = "past202203-open-a"
path = "./src/bin/a.rs"

[[bin]]
name = "past202203-open-b"
path = "./src/bin/b.rs"

[[bin]]
name = "past202203-open-c"
path = "./src/bin/c.rs"

[[bin]]
name = "past202203-open-d"
path = "./src/bin/d.rs"

[[bin]]
name = "past202203-open-e"
path = "./src/bin/e.rs"

[[bin]]
name = "past202203-open-f"
path = "./src/bin/f.rs"

[[bin]]
name = "past202203-open-g"
path = "./src/bin/g.rs"

[[bin]]
name = "past202203-open-h"
path = "./src/bin/h.rs"

[[bin]]
name = "past202203-open-i"
path = "./src/bin/i.rs"

[[bin]]
name = "past202203-open-j"
path = "./src/bin/j.rs"

[[bin]]
name = "past202203-open-k"
path = "./src/bin/k.rs"

[[bin]]
name = "past202203-open-l"
path = "./src/bin/l.rs"

[[bin]]
name = "past202203-open-m"
path = "./src/bin/m.rs"

[[bin]]
name = "past202203-open-n"
path = "./src/bin/n.rs"

[[bin]]
name = "past202203-open-o"
path = "./src/bin/o.rs"
