[package]
name = "past201912-open"
version = "0.1.0"
authors = ["emanon001 <emanon001@gmail.com>"]
edition = "2018"

[package.metadata.cargo-compete]
config = "../compete.toml"

[package.metadata.cargo-compete.bin]
a = { name = "past201912-open-a", problem = "https://atcoder.jp/contests/past201912-open/<FIXME: screen name of the problem>"}
b = { name = "past201912-open-b", problem = "https://atcoder.jp/contests/past201912-open/<FIXME: screen name of the problem>"}
c = { name = "past201912-open-c", problem = "https://atcoder.jp/contests/past201912-open/<FIXME: screen name of the problem>"}
d = { name = "past201912-open-d", problem = "https://atcoder.jp/contests/past201912-open/<FIXME: screen name of the problem>"}
e = { name = "past201912-open-e", problem = "https://atcoder.jp/contests/past201912-open/<FIXME: screen name of the problem>"}
f = { name = "past201912-open-f", problem = "https://atcoder.jp/contests/past201912-open/<FIXME: screen name of the problem>"}
g = { name = "past201912-open-g", problem = "https://atcoder.jp/contests/past201912-open/<FIXME: screen name of the problem>"}
h = { name = "past201912-open-h", problem = "https://atcoder.jp/contests/past201912-open/<FIXME: screen name of the problem>"}
i = { name = "past201912-open-i", problem = "https://atcoder.jp/contests/past201912-open/<FIXME: screen name of the problem>"}
j = { name = "past201912-open-j", problem = "https://atcoder.jp/contests/past201912-open/<FIXME: screen name of the problem>"}
k = { name = "past201912-open-k", problem = "https://atcoder.jp/contests/past201912-open/<FIXME: screen name of the problem>"}
l = { name = "past201912-open-l", problem = "https://atcoder.jp/contests/past201912-open/<FIXME: screen name of the problem>"}
m = { name = "past201912-open-m", problem = "https://atcoder.jp/contests/past201912-open/<FIXME: screen name of the problem>"}
n = { name = "past201912-open-n", problem = "https://atcoder.jp/contests/past201912-open/<FIXME: screen name of the problem>"}
o = { name = "past201912-open-o", problem = "https://atcoder.jp/contests/past201912-open/<FIXME: screen name of the problem>"}

# dependencies added to new project
[dependencies]
itertools = "=0.9.0"
itertools-num = "=0.1.3"
num = "=0.2.1"
ordered-float = "=1.0.2"
proconio = { version = "=0.3.6", features = ["derive"] }
regex = "=1.3.6"
whiteread = "=0.5.0"

[profile.release]
lto = true
panic = 'abort'

[[bin]]
name = "past201912-open-a"
path = "./src/bin/a.rs"

[[bin]]
name = "past201912-open-b"
path = "./src/bin/b.rs"

[[bin]]
name = "past201912-open-c"
path = "./src/bin/c.rs"

[[bin]]
name = "past201912-open-d"
path = "./src/bin/d.rs"

[[bin]]
name = "past201912-open-e"
path = "./src/bin/e.rs"

[[bin]]
name = "past201912-open-f"
path = "./src/bin/f.rs"

[[bin]]
name = "past201912-open-g"
path = "./src/bin/g.rs"

[[bin]]
name = "past201912-open-h"
path = "./src/bin/h.rs"

[[bin]]
name = "past201912-open-i"
path = "./src/bin/i.rs"

[[bin]]
name = "past201912-open-j"
path = "./src/bin/j.rs"

[[bin]]
name = "past201912-open-k"
path = "./src/bin/k.rs"

[[bin]]
name = "past201912-open-l"
path = "./src/bin/l.rs"

[[bin]]
name = "past201912-open-m"
path = "./src/bin/m.rs"

[[bin]]
name = "past201912-open-n"
path = "./src/bin/n.rs"

[[bin]]
name = "past201912-open-o"
path = "./src/bin/o.rs"
