[package]
name = "tdpc"
version = "0.1.0"
authors = ["emanon001 <emanon001@gmail.com>"]
edition = "2018"

[package.metadata.cargo-compete]
config = "../compete.toml"

[package.metadata.cargo-compete.bin]
a = { name = "tdpc-a", problem = "https://atcoder.jp/contests/tdpc/<FIXME: screen name of the problem>"}
b = { name = "tdpc-b", problem = "https://atcoder.jp/contests/tdpc/<FIXME: screen name of the problem>"}
c = { name = "tdpc-c", problem = "https://atcoder.jp/contests/tdpc/<FIXME: screen name of the problem>"}
d = { name = "tdpc-d", problem = "https://atcoder.jp/contests/tdpc/<FIXME: screen name of the problem>"}
e = { name = "tdpc-e", problem = "https://atcoder.jp/contests/tdpc/<FIXME: screen name of the problem>"}
f = { name = "tdpc-f", problem = "https://atcoder.jp/contests/tdpc/<FIXME: screen name of the problem>"}
g = { name = "tdpc-g", problem = "https://atcoder.jp/contests/tdpc/<FIXME: screen name of the problem>"}
h = { name = "tdpc-h", problem = "https://atcoder.jp/contests/tdpc/<FIXME: screen name of the problem>"}
i = { name = "tdpc-i", problem = "https://atcoder.jp/contests/tdpc/<FIXME: screen name of the problem>"}
j = { name = "tdpc-j", problem = "https://atcoder.jp/contests/tdpc/<FIXME: screen name of the problem>"}
k = { name = "tdpc-k", problem = "https://atcoder.jp/contests/tdpc/<FIXME: screen name of the problem>"}
l = { name = "tdpc-l", problem = "https://atcoder.jp/contests/tdpc/<FIXME: screen name of the problem>"}
m = { name = "tdpc-m", problem = "https://atcoder.jp/contests/tdpc/<FIXME: screen name of the problem>"}
n = { name = "tdpc-n", problem = "https://atcoder.jp/contests/tdpc/<FIXME: screen name of the problem>"}
o = { name = "tdpc-o", problem = "https://atcoder.jp/contests/tdpc/<FIXME: screen name of the problem>"}
p = { name = "tdpc-p", problem = "https://atcoder.jp/contests/tdpc/<FIXME: screen name of the problem>"}
q = { name = "tdpc-q", problem = "https://atcoder.jp/contests/tdpc/<FIXME: screen name of the problem>"}
r = { name = "tdpc-r", problem = "https://atcoder.jp/contests/tdpc/<FIXME: screen name of the problem>"}
s = { name = "tdpc-s", problem = "https://atcoder.jp/contests/tdpc/<FIXME: screen name of the problem>"}
t = { name = "tdpc-t", problem = "https://atcoder.jp/contests/tdpc/<FIXME: screen name of the problem>"}

# dependencies added to new project
# alga = "=0.9.3"
# ascii = "=1.0.0"
# bitset-fixed = "=0.1.0"
# either = "=1.5.3"
# fixedbitset = "=0.2.0"
# getrandom = "=0.1.14"
# im-rc = "=14.3.0"
# indexmap = "=1.3.2"
# lazy_static = "=1.4.0"
# libm = "=0.2.1"
# maplit = "=1.0.2"
# nalgebra = "=0.20.0"
# ndarray = "=0.13.0"
# permutohedron = "=0.2.4"
# petgraph = "=0.5.0"
# rand = { version = "=0.7.3", features = ["small_rng"] }
# rustc-hash = "=1.1.0"
# smallvec = "=1.2.0"
# superslice = "=1.0.0"
# text_io = "=0.1.8"
[dependencies]
itertools = "=0.9.0"
itertools-num = "=0.1.3"
num = "=0.2.1"
ordered-float = "=1.0.2"
proconio = { version = "=0.3.6", features = ["derive"] }
regex = "=1.3.6"
whiteread = "=0.5.0"

[profile.release]
lto = true
panic = 'abort'

[[bin]]
name = "tdpc-a"
path = "./src/bin/a.rs"

[[bin]]
name = "tdpc-b"
path = "./src/bin/b.rs"

[[bin]]
name = "tdpc-c"
path = "./src/bin/c.rs"

[[bin]]
name = "tdpc-d"
path = "./src/bin/d.rs"

[[bin]]
name = "tdpc-e"
path = "./src/bin/e.rs"

[[bin]]
name = "tdpc-f"
path = "./src/bin/f.rs"

[[bin]]
name = "tdpc-g"
path = "./src/bin/g.rs"

[[bin]]
name = "tdpc-h"
path = "./src/bin/h.rs"

[[bin]]
name = "tdpc-i"
path = "./src/bin/i.rs"

[[bin]]
name = "tdpc-j"
path = "./src/bin/j.rs"

[[bin]]
name = "tdpc-k"
path = "./src/bin/k.rs"

[[bin]]
name = "tdpc-l"
path = "./src/bin/l.rs"

[[bin]]
name = "tdpc-m"
path = "./src/bin/m.rs"

[[bin]]
name = "tdpc-n"
path = "./src/bin/n.rs"

[[bin]]
name = "tdpc-o"
path = "./src/bin/o.rs"

[[bin]]
name = "tdpc-p"
path = "./src/bin/p.rs"

[[bin]]
name = "tdpc-q"
path = "./src/bin/q.rs"

[[bin]]
name = "tdpc-r"
path = "./src/bin/r.rs"

[[bin]]
name = "tdpc-s"
path = "./src/bin/s.rs"

[[bin]]
name = "tdpc-t"
path = "./src/bin/t.rs"
