[package]
name = "agc035"
version = "0.1.0"
authors = ["emanon001 <emanon001@gmail.com>"]
edition = "2018"

[package.metadata.cargo-compete]
config = "../compete.toml"

[package.metadata.cargo-compete.bin]
a = { name = "agc035-a", problem = "https://atcoder.jp/contests/agc035/<FIXME: screen name of the problem>"}
b = { name = "agc035-b", problem = "https://atcoder.jp/contests/agc035/<FIXME: screen name of the problem>"}
c = { name = "agc035-c", problem = "https://atcoder.jp/contests/agc035/<FIXME: screen name of the problem>"}
d = { name = "agc035-d", problem = "https://atcoder.jp/contests/agc035/<FIXME: screen name of the problem>"}
e = { name = "agc035-e", problem = "https://atcoder.jp/contests/agc035/<FIXME: screen name of the problem>"}
f = { name = "agc035-f", problem = "https://atcoder.jp/contests/agc035/<FIXME: screen name of the problem>"}

# dependencies added to new project
[dependencies]
proconio = "*"

[profile.release]
lto = true
panic = 'abort'

[[bin]]
name = "agc035-a"
path = "./src/bin/a.rs"

[[bin]]
name = "agc035-b"
path = "./src/bin/b.rs"

[[bin]]
name = "agc035-c"
path = "./src/bin/c.rs"

[[bin]]
name = "agc035-d"
path = "./src/bin/d.rs"

[[bin]]
name = "agc035-e"
path = "./src/bin/e.rs"

[[bin]]
name = "agc035-f"
path = "./src/bin/f.rs"
