[package]
name = "code-festival-2017-qualc"
version = "0.1.0"
authors = ["emanon001 <emanon001@gmail.com>"]
edition = "2018"

[package.metadata.cargo-compete]
config = "../compete.toml"

[package.metadata.cargo-compete.bin]
a = { name = "code-festival-2017-qualc-a", problem = "https://atcoder.jp/contests/code-festival-2017-qualc/<FIXME: screen name of the problem>"}
b = { name = "code-festival-2017-qualc-b", problem = "https://atcoder.jp/contests/code-festival-2017-qualc/<FIXME: screen name of the problem>"}
c = { name = "code-festival-2017-qualc-c", problem = "https://atcoder.jp/contests/code-festival-2017-qualc/<FIXME: screen name of the problem>"}
d = { name = "code-festival-2017-qualc-d", problem = "https://atcoder.jp/contests/code-festival-2017-qualc/<FIXME: screen name of the problem>"}
e = { name = "code-festival-2017-qualc-e", problem = "https://atcoder.jp/contests/code-festival-2017-qualc/<FIXME: screen name of the problem>"}
f = { name = "code-festival-2017-qualc-f", problem = "https://atcoder.jp/contests/code-festival-2017-qualc/<FIXME: screen name of the problem>"}

# dependencies added to new project
[dependencies]
proconio = "*"

[profile.release]
lto = true
panic = 'abort'

[[bin]]
name = "code-festival-2017-qualc-a"
path = "./src/bin/a.rs"

[[bin]]
name = "code-festival-2017-qualc-b"
path = "./src/bin/b.rs"

[[bin]]
name = "code-festival-2017-qualc-c"
path = "./src/bin/c.rs"

[[bin]]
name = "code-festival-2017-qualc-d"
path = "./src/bin/d.rs"

[[bin]]
name = "code-festival-2017-qualc-e"
path = "./src/bin/e.rs"

[[bin]]
name = "code-festival-2017-qualc-f"
path = "./src/bin/f.rs"
