[package]
name = "sumitrust2019"
version = "0.1.0"
authors = ["emanon001 <emanon001@gmail.com>"]
edition = "2018"

[package.metadata.cargo-compete]
config = "../compete.toml"

[package.metadata.cargo-compete.bin]
a = { name = "sumitrust2019-a", problem = "https://atcoder.jp/contests/sumitrust2019/<FIXME: screen name of the problem>"}
b = { name = "sumitrust2019-b", problem = "https://atcoder.jp/contests/sumitrust2019/<FIXME: screen name of the problem>"}
c = { name = "sumitrust2019-c", problem = "https://atcoder.jp/contests/sumitrust2019/<FIXME: screen name of the problem>"}
d = { name = "sumitrust2019-d", problem = "https://atcoder.jp/contests/sumitrust2019/<FIXME: screen name of the problem>"}
e = { name = "sumitrust2019-e", problem = "https://atcoder.jp/contests/sumitrust2019/<FIXME: screen name of the problem>"}
f = { name = "sumitrust2019-f", problem = "https://atcoder.jp/contests/sumitrust2019/<FIXME: screen name of the problem>"}

# dependencies added to new project
[dependencies]
proconio = "*"

[profile.release]
lto = true
panic = 'abort'

[[bin]]
name = "sumitrust2019-a"
path = "./src/bin/a.rs"

[[bin]]
name = "sumitrust2019-b"
path = "./src/bin/b.rs"

[[bin]]
name = "sumitrust2019-c"
path = "./src/bin/c.rs"

[[bin]]
name = "sumitrust2019-d"
path = "./src/bin/d.rs"

[[bin]]
name = "sumitrust2019-e"
path = "./src/bin/e.rs"

[[bin]]
name = "sumitrust2019-f"
path = "./src/bin/f.rs"
