[package]
name = "cf17-final"
version = "0.1.0"
authors = ["emanon001 <emanon001@gmail.com>"]
edition = "2018"

[package.metadata.cargo-compete]
config = "../compete.toml"

[package.metadata.cargo-compete.bin]
a = { name = "cf17-final-a", problem = "https://atcoder.jp/contests/cf17-final/<FIXME: screen name of the problem>"}
b = { name = "cf17-final-b", problem = "https://atcoder.jp/contests/cf17-final/<FIXME: screen name of the problem>"}
c = { name = "cf17-final-c", problem = "https://atcoder.jp/contests/cf17-final/<FIXME: screen name of the problem>"}
d = { name = "cf17-final-d", problem = "https://atcoder.jp/contests/cf17-final/<FIXME: screen name of the problem>"}
e = { name = "cf17-final-e", problem = "https://atcoder.jp/contests/cf17-final/<FIXME: screen name of the problem>"}
f = { name = "cf17-final-f", problem = "https://atcoder.jp/contests/cf17-final/<FIXME: screen name of the problem>"}
g = { name = "cf17-final-g", problem = "https://atcoder.jp/contests/cf17-final/<FIXME: screen name of the problem>"}
h = { name = "cf17-final-h", problem = "https://atcoder.jp/contests/cf17-final/<FIXME: screen name of the problem>"}
i = { name = "cf17-final-i", problem = "https://atcoder.jp/contests/cf17-final/<FIXME: screen name of the problem>"}
j = { name = "cf17-final-j", problem = "https://atcoder.jp/contests/cf17-final/<FIXME: screen name of the problem>"}

# dependencies added to new project
[dependencies]
proconio = "*"
regex = "=1.3.3"

[profile.release]
lto = true
panic = 'abort'

[[bin]]
name = "cf17-final-a"
path = "./src/bin/a.rs"

[[bin]]
name = "cf17-final-b"
path = "./src/bin/b.rs"

[[bin]]
name = "cf17-final-c"
path = "./src/bin/c.rs"

[[bin]]
name = "cf17-final-d"
path = "./src/bin/d.rs"

[[bin]]
name = "cf17-final-e"
path = "./src/bin/e.rs"

[[bin]]
name = "cf17-final-f"
path = "./src/bin/f.rs"

[[bin]]
name = "cf17-final-g"
path = "./src/bin/g.rs"

[[bin]]
name = "cf17-final-h"
path = "./src/bin/h.rs"

[[bin]]
name = "cf17-final-i"
path = "./src/bin/i.rs"

[[bin]]
name = "cf17-final-j"
path = "./src/bin/j.rs"
