[package]
name = "joi2007ho"
version = "0.1.0"
authors = ["emanon001 <emanon001@gmail.com>"]
edition = "2018"

[package.metadata.cargo-compete]
config = "../compete.toml"

[package.metadata.cargo-compete.bin]
a = { name = "joi2007ho-a", problem = "https://atcoder.jp/contests/joi2007ho/<FIXME: screen name of the problem>"}
b = { name = "joi2007ho-b", problem = "https://atcoder.jp/contests/joi2007ho/<FIXME: screen name of the problem>"}
c = { name = "joi2007ho-c", problem = "https://atcoder.jp/contests/joi2007ho/<FIXME: screen name of the problem>"}
d = { name = "joi2007ho-d", problem = "https://atcoder.jp/contests/joi2007ho/<FIXME: screen name of the problem>"}
e = { name = "joi2007ho-e", problem = "https://atcoder.jp/contests/joi2007ho/<FIXME: screen name of the problem>"}

# dependencies added to new project
[dependencies]
proconio = "*"

[profile.release]
lto = true
panic = 'abort'

[[bin]]
name = "joi2007ho-a"
path = "./src/bin/a.rs"

[[bin]]
name = "joi2007ho-b"
path = "./src/bin/b.rs"

[[bin]]
name = "joi2007ho-c"
path = "./src/bin/c.rs"

[[bin]]
name = "joi2007ho-d"
path = "./src/bin/d.rs"

[[bin]]
name = "joi2007ho-e"
path = "./src/bin/e.rs"
