[package]
name = "agc043"
version = "0.1.0"
authors = ["emanon001 <emanon001@gmail.com>"]
edition = "2018"

[package.metadata.cargo-compete]
config = "../compete.toml"

[package.metadata.cargo-compete.bin]
a = { name = "agc043-a", problem = "https://atcoder.jp/contests/agc043/<FIXME: screen name of the problem>"}
b = { name = "agc043-b", problem = "https://atcoder.jp/contests/agc043/<FIXME: screen name of the problem>"}
c = { name = "agc043-c", problem = "https://atcoder.jp/contests/agc043/<FIXME: screen name of the problem>"}
d = { name = "agc043-d", problem = "https://atcoder.jp/contests/agc043/<FIXME: screen name of the problem>"}
e = { name = "agc043-e", problem = "https://atcoder.jp/contests/agc043/<FIXME: screen name of the problem>"}
f = { name = "agc043-f", problem = "https://atcoder.jp/contests/agc043/<FIXME: screen name of the problem>"}

# dependencies added to new project
[dependencies]
proconio = "*"

[profile.release]
lto = true
panic = 'abort'

[[bin]]
name = "agc043-a"
path = "./src/bin/a.rs"

[[bin]]
name = "agc043-b"
path = "./src/bin/b.rs"

[[bin]]
name = "agc043-c"
path = "./src/bin/c.rs"

[[bin]]
name = "agc043-d"
path = "./src/bin/d.rs"

[[bin]]
name = "agc043-e"
path = "./src/bin/e.rs"

[[bin]]
name = "agc043-f"
path = "./src/bin/f.rs"
