[package]
name = "dp"
version = "0.1.0"
authors = ["emanon001 <emanon001@gmail.com>"]
edition = "2018"

[package.metadata.cargo-compete]
config = "../compete.toml"

[package.metadata.cargo-compete.bin]
a = { name = "dp-a", problem = "https://atcoder.jp/contests/dp/<FIXME: screen name of the problem>"}
b = { name = "dp-b", problem = "https://atcoder.jp/contests/dp/<FIXME: screen name of the problem>"}
c = { name = "dp-c", problem = "https://atcoder.jp/contests/dp/<FIXME: screen name of the problem>"}
d = { name = "dp-d", problem = "https://atcoder.jp/contests/dp/<FIXME: screen name of the problem>"}
e = { name = "dp-e", problem = "https://atcoder.jp/contests/dp/<FIXME: screen name of the problem>"}
f = { name = "dp-f", problem = "https://atcoder.jp/contests/dp/<FIXME: screen name of the problem>"}
g = { name = "dp-g", problem = "https://atcoder.jp/contests/dp/<FIXME: screen name of the problem>"}
h = { name = "dp-h", problem = "https://atcoder.jp/contests/dp/<FIXME: screen name of the problem>"}
i = { name = "dp-i", problem = "https://atcoder.jp/contests/dp/<FIXME: screen name of the problem>"}
j = { name = "dp-j", problem = "https://atcoder.jp/contests/dp/<FIXME: screen name of the problem>"}
k = { name = "dp-k", problem = "https://atcoder.jp/contests/dp/<FIXME: screen name of the problem>"}
l = { name = "dp-l", problem = "https://atcoder.jp/contests/dp/<FIXME: screen name of the problem>"}
m = { name = "dp-m", problem = "https://atcoder.jp/contests/dp/<FIXME: screen name of the problem>"}
n = { name = "dp-n", problem = "https://atcoder.jp/contests/dp/<FIXME: screen name of the problem>"}
o = { name = "dp-o", problem = "https://atcoder.jp/contests/dp/<FIXME: screen name of the problem>"}
p = { name = "dp-p", problem = "https://atcoder.jp/contests/dp/<FIXME: screen name of the problem>"}
q = { name = "dp-q", problem = "https://atcoder.jp/contests/dp/<FIXME: screen name of the problem>"}
r = { name = "dp-r", problem = "https://atcoder.jp/contests/dp/<FIXME: screen name of the problem>"}
s = { name = "dp-s", problem = "https://atcoder.jp/contests/dp/<FIXME: screen name of the problem>"}
t = { name = "dp-t", problem = "https://atcoder.jp/contests/dp/<FIXME: screen name of the problem>"}
u = { name = "dp-u", problem = "https://atcoder.jp/contests/dp/<FIXME: screen name of the problem>"}
v = { name = "dp-v", problem = "https://atcoder.jp/contests/dp/<FIXME: screen name of the problem>"}
w = { name = "dp-w", problem = "https://atcoder.jp/contests/dp/<FIXME: screen name of the problem>"}
x = { name = "dp-x", problem = "https://atcoder.jp/contests/dp/<FIXME: screen name of the problem>"}
y = { name = "dp-y", problem = "https://atcoder.jp/contests/dp/<FIXME: screen name of the problem>"}
z = { name = "dp-z", problem = "https://atcoder.jp/contests/dp/<FIXME: screen name of the problem>"}

# dependencies added to new project
# alga = "=0.9.3"
# ascii = "=1.0.0"
# bitset-fixed = "=0.1.0"
# either = "=1.5.3"
# fixedbitset = "=0.2.0"
# getrandom = "=0.1.14"
# im-rc = "=14.3.0"
# indexmap = "=1.3.2"
# lazy_static = "=1.4.0"
# libm = "=0.2.1"
# maplit = "=1.0.2"
# nalgebra = "=0.20.0"
# ndarray = "=0.13.0"
# permutohedron = "=0.2.4"
# petgraph = "=0.5.0"
# rand = { version = "=0.7.3", features = ["small_rng"] }
# rustc-hash = "=1.1.0"
# smallvec = "=1.2.0"
# superslice = "=1.0.0"
# text_io = "=0.1.8"
[dependencies]
itertools = "=0.9.0"
itertools-num = "=0.1.3"
num = "=0.2.1"
ordered-float = "=1.0.2"
proconio = { version = "=0.3.6", features = ["derive"] }
regex = "=1.3.6"
whiteread = "=0.5.0"

[profile.release]
lto = true
panic = 'abort'

[[bin]]
name = "dp-a"
path = "./src/bin/a.rs"

[[bin]]
name = "dp-b"
path = "./src/bin/b.rs"

[[bin]]
name = "dp-c"
path = "./src/bin/c.rs"

[[bin]]
name = "dp-d"
path = "./src/bin/d.rs"

[[bin]]
name = "dp-e"
path = "./src/bin/e.rs"

[[bin]]
name = "dp-f"
path = "./src/bin/f.rs"

[[bin]]
name = "dp-g"
path = "./src/bin/g.rs"

[[bin]]
name = "dp-h"
path = "./src/bin/h.rs"

[[bin]]
name = "dp-i"
path = "./src/bin/i.rs"

[[bin]]
name = "dp-j"
path = "./src/bin/j.rs"

[[bin]]
name = "dp-k"
path = "./src/bin/k.rs"

[[bin]]
name = "dp-l"
path = "./src/bin/l.rs"

[[bin]]
name = "dp-m"
path = "./src/bin/m.rs"

[[bin]]
name = "dp-n"
path = "./src/bin/n.rs"

[[bin]]
name = "dp-o"
path = "./src/bin/o.rs"

[[bin]]
name = "dp-p"
path = "./src/bin/p.rs"

[[bin]]
name = "dp-q"
path = "./src/bin/q.rs"

[[bin]]
name = "dp-r"
path = "./src/bin/r.rs"

[[bin]]
name = "dp-s"
path = "./src/bin/s.rs"

[[bin]]
name = "dp-t"
path = "./src/bin/t.rs"

[[bin]]
name = "dp-u"
path = "./src/bin/u.rs"

[[bin]]
name = "dp-v"
path = "./src/bin/v.rs"

[[bin]]
name = "dp-w"
path = "./src/bin/w.rs"

[[bin]]
name = "dp-x"
path = "./src/bin/x.rs"

[[bin]]
name = "dp-y"
path = "./src/bin/y.rs"

[[bin]]
name = "dp-z"
path = "./src/bin/z.rs"
