[package]
name = "dwacon6th-prelims"
version = "0.1.0"
authors = ["emanon001 <emanon001@gmail.com>"]
edition = "2018"

[package.metadata.cargo-compete]
config = "../compete.toml"

[package.metadata.cargo-compete.bin]
a = { name = "dwacon6th-prelims-a", problem = "https://atcoder.jp/contests/dwacon6th-prelims/<FIXME: screen name of the problem>"}
b = { name = "dwacon6th-prelims-b", problem = "https://atcoder.jp/contests/dwacon6th-prelims/<FIXME: screen name of the problem>"}
c = { name = "dwacon6th-prelims-c", problem = "https://atcoder.jp/contests/dwacon6th-prelims/<FIXME: screen name of the problem>"}
d = { name = "dwacon6th-prelims-d", problem = "https://atcoder.jp/contests/dwacon6th-prelims/<FIXME: screen name of the problem>"}
e = { name = "dwacon6th-prelims-e", problem = "https://atcoder.jp/contests/dwacon6th-prelims/<FIXME: screen name of the problem>"}

# dependencies added to new project
[dependencies]
proconio = "*"

[profile.release]
lto = true
panic = 'abort'

[[bin]]
name = "dwacon6th-prelims-a"
path = "./src/bin/a.rs"

[[bin]]
name = "dwacon6th-prelims-b"
path = "./src/bin/b.rs"

[[bin]]
name = "dwacon6th-prelims-c"
path = "./src/bin/c.rs"

[[bin]]
name = "dwacon6th-prelims-d"
path = "./src/bin/d.rs"

[[bin]]
name = "dwacon6th-prelims-e"
path = "./src/bin/e.rs"
