[package]
name = "agc009"
version = "0.1.0"
authors = ["emanon001 <emanon001@gmail.com>"]
edition = "2018"

[package.metadata.cargo-compete]
config = "../compete.toml"

[package.metadata.cargo-compete.bin]
a = { name = "agc009-a", problem = "https://atcoder.jp/contests/agc009/<FIXME: screen name of the problem>"}
b = { name = "agc009-b", problem = "https://atcoder.jp/contests/agc009/<FIXME: screen name of the problem>"}
c = { name = "agc009-c", problem = "https://atcoder.jp/contests/agc009/<FIXME: screen name of the problem>"}
d = { name = "agc009-d", problem = "https://atcoder.jp/contests/agc009/<FIXME: screen name of the problem>"}
e = { name = "agc009-e", problem = "https://atcoder.jp/contests/agc009/<FIXME: screen name of the problem>"}

# dependencies added to new project
[dependencies]
proconio = "*"

[profile.release]
lto = true
panic = 'abort'

[[bin]]
name = "agc009-a"
path = "./src/bin/a.rs"

[[bin]]
name = "agc009-b"
path = "./src/bin/b.rs"

[[bin]]
name = "agc009-c"
path = "./src/bin/c.rs"

[[bin]]
name = "agc009-d"
path = "./src/bin/d.rs"

[[bin]]
name = "agc009-e"
path = "./src/bin/e.rs"
